### ISSUE TITLE
Links on /cn/ not working

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/cn#1]
Looks like the "main" site is working: https://swiftweekly.github.io/cn/

But clicking any issue link takes you to `https://swiftweekly.github.io/issue-##`

It should be `https://swiftweekly.github.io/cn/issue-##`.

For example: https://swiftweekly.github.io/cn/issue-121/

So everything appears to be mostly working...

**Comment by wongzigii** [comment]
Fixed in https://github.com/SwiftWeekly/cn/commit/162d94203a05fa59eade79c9661cac7abed0620f

**Comment by jessesquires** [comment]
thanks @wongzigii ! 🎉
