### ISSUE TITLE
Resolve the submodule issue

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/cn#2]
Do we still need the submodule for `https://github.com/swiftweeklycn/_posts.git` ?

Should we add the main site (`https://github.com/SwiftWeekly/swiftweekly.github.io.git`) as a submodule instead?

**Comment by wongzigii** [comment]
Alright, I've just removed submodule and copy all posts to `cn/_posts`. We no more need submodule now. Cheers

**Comment by jessesquires** [comment]
thanks @wongzigii ! 🎉
